-name: restart switchd
 service: name=switchd state=restarted

-name: reload networking
 service: name=networking state=reload
 
-name: restart ptmd
 service: name=ptmd state=restarted
 
-name: restart quagga
 service: name=quagga state=restarted
