-interfaces
 -switch1
   loopback: "192.168.201.1"
   int_num:
    swp1:
    swp2:
   bonds:
    bond0:
     memebers: ["swp1"," swp2"]
     address: "192.168.200.1/30"
  bridges:
   vlan_aware:
    name: "bridge"
    pvid: "1"
    vids: "100 200"
    members: ["swp3","swp4","swp5"]
    svi:
     bridge.100:
      ip: "192.168.202.1/24"
  
 
 -switch2
   -switch1
   loopback: "192.168.201.2"
   int_num:
    swp1:
    swp2:
   bonds:
    bond0:
     memebers: ["swp1"," swp2"]
     address: "192.168.200.2/30"
  bridges:
   vlan_aware:
    name: "bridge"
    pvid: "1"
    vids: "100 200"
    members: ["swp3","swp4","swp5"]
    svi:
     bridge.200:
      ip: "192.168.203.1/24"
